default_language_version:
  python: python3.9

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
    exclude: ^.*\.md$
  - id: end-of-file-fixer
  - id: debug-statements
  - id: no-commit-to-branch
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: detect-private-key
  - id: detect-aws-credentials
    args: [--allow-missing-credentials]
  - id: check-merge-conflict

- repo: https://github.com/jorisroovers/gitlint
  rev: v0.16.0
  hooks:
  - id: gitlint

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.2.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/adrienverge/yamllint
  rev: v1.26.3
  hooks:
  - id: yamllint

- repo: https://github.com/timothycrosley/isort
  rev: 5.9.3
  hooks:
  - id: isort
    additional_dependencies: ['.[pyproject]']

- repo: https://github.com/ambv/black
  rev: 21.9b0
  hooks:
  - id: black
    name: black-code-formatter
    additional_dependencies: ['.[pyproject]']

- repo: https://github.com/myint/autoflake
  rev: v1.4
  hooks:
  - id: autoflake
    args: [--in-place, --remove-all-unused-imports, --remove-unused-variable]

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    files: ^dqr/
    additional_dependencies: [flake8-print, flake8-docstrings, '.[flake8]']
